// All player-visible text. Switching language = swapping this file's data.
export const STR = {
  title: "Primal Dread",
  subtitle: "Escape the dinosaurs. Survive the night.",
  play: "Play",
  resume: "Resume",
  loading: "Loading the forest…",
  intro: "You wake up alone in an old building. Something enormous is walking around outside. Find food, loot chests, and reach the tree hut deeper in the forest — quietly.",
  controlsDesktop: "WASD move · Q/E previous/next item · Mouse look · Z (or Shift) run · C sneak · Space jump · F interact · Left-click use item / attack · 1–8 hotbar · Esc menu",
  controlsTouch: "Left stick: move · drag right side: look · buttons: sprint, sneak, jump, use/attack · tap an item to select it · a named button (Open, Sleep, Cook...) appears whenever something is in reach · ❚❚ top-left pauses",
  // update 23: mobile-only controls mode chooser (Controls menu)
  ctlModeTitle: "Controls mode — this device",
  ctlModeTouch: "On-screen controls",
  ctlModeClassic: "Classic (keyboard + mouse)",
  ctlModeTouchNote: "Left stick: move · drag the right side: look · buttons: run, sneak, jump, use/attack · tap a hotbar item to select it · a named button (Open, Sleep, Cook...) appears whenever something is in reach · the ❚❚ button top-left pauses the game.",
  ctlModeClassicNote: "Plays exactly like on a PC — connect a keyboard and a mouse to your device. The full key list is below.",
  controlsPad: "Gamepad: sticks move/look · A interact · B jump · RT/X use or attack · LB sneak · L3 sprint",

  goalStart: "Find something to eat. A knife is said to lie in a chest where the forest path begins.",
  goalKnife: "Follow the forest path to the tree hut. Watch the T-Rex — sneak when it is near.",
  goalHut: "You reached the tree hut. Cook meat in the kitchen, and sleep in a bed at night.",
  goalSurvive: "Survive until day 3. The forest is more dangerous at night.",

  day: "Day",
  timeDay: "Daytime",
  timeDusk: "Dusk",
  timeNight: "Night",
  timeDawn: "Dawn",

  interact: "F",
  openChest: "Open chest",
  pickUp: "Pick up",
  pickApple: "Pick apple",
  sleep: "Sleep until morning",
  sleepNotNight: "You can only sleep at night",
  cookPrompt: "Cook",
  cookFirePrompt: "Cook meat on the campfire",
  nothingToCook: "You have nothing raw to cook",
  nothingToCookFire: "You have no raw meat to roast",
  noEggOnFire: "No pan — you cannot cook eggs on a campfire. The hut kitchen has one.",
  cooking: "Cooking…",
  twigCrack: "A branch cracks under your foot…",

  talkTo: "Talk to Bill",
  billTitle: "Bill the farmer",
  billLines: [
    "Well now — another living soul! Haven't seen one of those in a while. Name's Bill.",
    "Sit yourself down at the table if your legs are tired. Rest does a body good.",
  ],
  billAskRex: "Ask about the T-Rexes",
  billAskSafe: "How do I stay safe?",
  billRexLines: [
    "The big ones? Meanest things the forest ever grew. They can't be killed — believe me, folk have tried with more than a kitchen knife.",
    "They hunt with their EARS first. Run around making a racket and every one of them within a valley will come looking. And once one gets a bite of you, it knows your smell — hiding won't save you till the next sunrise.",
    "Although… old Hans at the camping swears a man once drew blood from one with a knife lashed to a long shaft. Blood, maybe. Killing it? Nothing you or I can carry kills one of those.",
  ],
  billSafeLines: [
    "Move slow and quiet — crouch if you can. Watch for dry branches, they crack loud enough to wake the dead.",
    "If one spots you, put a boulder or a fat tree between you and it, and stay put. The ground floor of the old temple is blind to them — and my hut here, they can't reach. Up on the temple's second floor, mind the holes. That neck is longer than you think.",
  ],
  billBack: "Back",
  billTradeBtn: "Trade 10 eggs for 1 bandage",
  billNoEggs: "Come back when you've got ten eggs, friend.",
  billTraded: "Pleasure doing business! Careful out there.",
  billLeave: "Leave",

  storageTitle: "Personal storage",
  storageHint: "Click an item to move it between your bag and the chest.",
  openStorage: "Open your storage chest",
  storageFull: "The chest is full",

  craftTitle: "Crafting table",
  craftHint: "Old tools rest here. Some of these will matter more in updates to come.",
  useCraft: "Use crafting table",
  craftBtn: "Craft",
  craftMissing: "You are missing materials",
  crafted: "Crafted",
  close: "Close",

  wolfImmune: "The blade passes through its hide — only SILVER can wound a werewolf.",
  daggerFound: "A SILVER DAGGER — the only blade a werewolf fears.",

  openDoor: "Open the door",
  closeDoor: "Close the door",
  sitDown: "Sit down and rest",
  standUp: "Stand up",
  sitResting: "Resting… energy recovers all the way",

  controlsTitle: "Controls",
  controlsBtn: "Controls",
  controlsList: [
    ["W A S D", "Move"],
    ["Mouse", "Look around"],
    ["Q / E", "Previous / next hotbar item (wraps round from 8 to 1)"],
    ["Z or Shift", "Run (drains energy and hunger faster)"],
    ["C", "Sneak on/off (quiet — T-Rexes hear less)"],
    ["Space", "Jump (costs energy)"],
    ["F", "Interact: chests, doors, beds, cooking, talking, sitting"],
    ["Left-click", "Use the selected item: eat food, drink, apply bandage — or attack with a blade"],
    ["Right-click", "Drop ONE of the selected item — HOLD ~2s to drop the whole stack (10 min to pick it back up)"],
    ["1 – 8", "Select a hotbar slot"],
    ["Arrows / Enter", "Navigate and choose in any menu"],
    ["Esc", "Pause menu"],
    ["Shift + Esc", "Release the mouse without pausing"],
  ],

  hintEat: "eat",
  hintDrink: "drink",
  hintBandage: "apply",
  hintAttack: "attack",
  hintCookFirst: "raw — cook it at the campfire or the hut kitchen",
  hintCookKitchen: "raw — cook it in the hut kitchen (needs a pan)",
  hintNoUse: "no direct use — a keepsake of the hunt",
  hintLeftClick: "Left-click",
  hintUseBtn: "USE",

  chestEmpty: "Empty — someone got here first",
  snakeBite: "A SNAKE! It bites you and coils back into the chest…",
  found: "Found",
  inventoryFull: "Your hands are full — inventory is full",
  needsCooking: "Raw. It needs to be cooked in a kitchen first",
  noEffect: "Not edible",
  knifeEquipped: "Knife — click to attack",
  noWeapon: "You have no weapon",
  knifeUseless: "Your knife glances off its hide. You cannot kill this. RUN.",
  fullHealth: "Health is already full",
  fullEnergy: "Energy is already full",
  fullHunger: "You are not hungry",
  tooTired: "Too exhausted to sprint",
  tooTiredJump: "Too exhausted to jump",

  ateApple: "Apple — the vitamins wake you up a little",
  usedBandage: "Bandage applied",
  drankEnergy: "Energy drink — you feel faster already",

  trexNear: "The ground trembles…",
  trexSpotted: "IT HAS SEEN YOU — RUN!",
  trexHeard: "It heard something. It is coming to look…",
  trexLost: "It lost your trail. Breathe.",
  windowWarning: "Get away from the window!",
  nightFalls: "Night falls. You hear howling in the forest…",
  morning: "Morning. The wolves retreat.",
  safeRoom: "This room is safe. Nothing can reach you here.",
  hutSafe: "The tree hut is safe — for now.",
  slept: "You slept. Health and energy restored.",

  killedPig: "You killed the pig",
  killedChicken: "You killed the chicken",
  killedWolf: "You killed the werewolf",
  killedCroc: "You killed the crocodile",

  dead: "You died",
  deadEaten: "Eaten. The forest is quiet again.",
  deadWolf: "Torn apart by a werewolf.",
  deadHunger: "You starved in the middle of a forest full of food.",
  deadCow: "Trampled by a cow you should have left in peace.",
  deadElisia: "Elisia's claws found you.",
  deadAlio: "Torn open by an Alioramus.",
  deadCactus: "Killed by a cactus. Really.",
  // ---- update 36: the desert ----
  thirstWarn: "Your throat burns \u2014 find water.",
  bottleEmpty: "empty \u2014 fill it at any water",
  bottleFull: "full \u00b7 %t of water left",
  noBottle: "You have nothing to catch the water in.",
  bottleFilled: "The bottle is full.",
  fillBottle: "Fill the bottle",
  cactusWater: "Cactus water \u2014 the bottle is full again.",
  cactusHurt: "The spines get you. Careful with that knife.",
  talkToIdris: "Talk to Idris",
  idrisTitle: "Idris",
  idrisFirst: [
    "Sit, sit. Not many come over the bridges. The sand eats the careless \u2014 and the ones with teeth eat the rest.",
    "Rule one out here: water. Your body dries like a fig in this sun. Keep drinking or you stop thinking, then you stop walking.",
    "Take my old canteen. Fill it at the river, at the pool by the palm, or cut a cactus if you must \u2014 mind the spines. My tent is shade, and nothing hunts you under my roof.",
  ],
  idrisAgain: [
    "Still alive. Good. Keep the canteen full and keep to the shade when you can.",
    "The grey ones by the river hunt with their ears \u2014 walk, do not run. The brown ones deeper in hunt with their eyes. Keep something between you and them.",
  ],
  idrisLost: [
    "The desert took it? It takes everything, in the end. Here \u2014 I have another. Do not lose this one.",
  ],
  idrisTake: "Take the canteen",
  idrisBye: "Thank you",
  bottleGot: "Idris's canteen \u2014 fill it at any water.",
  alioImmune: "The blade skids off its scales \u2014 nothing you carry can kill it. RUN.",
  alioLost: "It stops at the water's edge and watches you go.",
  alioSteal: "It snatches the meat from your pack and tears into it \u2014 RUN!",
  alioSeen: "It has SEEN you \u2014 RUN!",
  alioHeard: "It HEARD that \u2014 RUN!",
  // ---- update 35: Elisia ----
  elisiaKiss: "Elisia kisses you. Warmth floods through you.",
  elisiaGift: "She gives you a T-Rex dagger and a bottle of holy water.",
  elisiaRise: "Elisia smiles \u2014 and rises into the sky.",
  elisiaUnharmed: "Your blow passes through her light.",
  elisiaEvil: "ELISIA'S EYES TURN RED \u2014 RUN!",
  elisiaImmune: "Nothing but a T-Rex's tooth can hurt her!",
  elisiaSlain: "ELISIA FALLS. The grey mist thins.",
  huntElisia: "ELISIA",
  holyWaterHint: "The water glows softly in your hand.",
  unholyWaterHint: "The bottle is cold to the touch.",
  unholyTiaraHint: "The gems pulse faintly under your thumb.",
  respawn: "Wake up",
  deathHint: "Your belongings stayed where you fell. You have 15 minutes to go back and recover them.",

  win: "You survived",
  winText: "Three days among the dinosaurs — and you are still breathing. The forest is yours now — the river, the desert and everything beyond are waiting.",
  keepPlaying: "Keep surviving",

  items: {
    bandage:      { name: "Bandage",       desc: "+10% health" },
    energy_drink: { name: "Energy drink",  desc: "+10% energy" },
    apple:        { name: "Apple",         desc: "+10% food, boosts low energy to 25%" },
    raw_pork:     { name: "Raw pork",      desc: "Cook it in a kitchen" },
    cooked_pork:  { name: "Cooked pork",   desc: "+10% food" },
    raw_chicken:  { name: "Raw chicken",   desc: "Cook it in a kitchen" },
    cooked_chicken:{ name: "Cooked chicken", desc: "+10% food" },
    egg:          { name: "Egg",           desc: "Cook it in a kitchen" },
    cooked_eggs:  { name: "Cooked eggs",   desc: "+10% food, +5% energy" },
    raw_wolf:     { name: "Raw wolf meat", desc: "Cook it in a kitchen" },
    cooked_wolf:  { name: "Cooked wolf meat", desc: "+15% food" },
    wolf_fur:     { name: "Wolf fur",      desc: "A werewolf's pelt — four of these sew a wolf-fur cloak" },
    wolf_tooth:   { name: "Wolf tooth", desc: "A fang pried from a werewolf. One in a great many carries one" },
    knife:        { name: "Survival knife", desc: "A weapon — useless against werewolves" },
    silver_dagger:{ name: "Silver dagger", desc: "The only blade that can kill a werewolf" },
    fur_cloak:    { name: "Wolf-fur cloak", desc: "Warm and heavy — four hunts stitched into one cloak" },
    spear:        { name: "Bound spear", desc: "A knife lashed to a long shaft. Thrown hard, it brings down wolves and crocs — a T-Rex's hide only shrugs it off" },
    raw_trex:     { name: "Raw T-Rex meat", desc: "Cook it over any fire" },
    cooked_trex:  { name: "T-Rex steak", desc: "+25% food, +10% energy — the meal of a lifetime" },
    trex_tooth:   { name: "T-Rex tooth", desc: "A trophy nobody will believe" },
    // update 35: Elisia's gifts and what her dark form leaves behind
    trex_dagger:  { name: "T-Rex dagger", desc: "A dagger ground from a T-Rex tooth. The only blade Elisia's dark form fears" },
    imp_tooth:    { name: "T-Imperator tooth", desc: "Black, serrated, needle-sharp. One in five Imperators leaves one" },
    imp_dagger:   { name: "T-Imperator dagger", desc: "A blade of black Imperator tooth. Cuts Elisia's dark form twice as deep" },
    // update 39: Eternius City
    fossil:       { name: "Fossil", desc: "A small skeleton in stone. Worth a fortune to the right Eternial" },
    gold_statuette: { name: "Golden statuette", desc: "A pocket-sized Eternial in solid gold. Worth a king's ransom in Eternius" },
    vault_key:    { name: "Vault key", desc: "The king's key to the vault behind the cavern river" },
    et_dagger:    { name: "Eternial dagger", desc: "Gold and green stone. Sharper than iron or silver — but no Eternial blade can touch Elisia or a werewolf" },
    et_sword:     { name: "Eternial sword", desc: "A long golden blade with a winged hilt. The heaviest cut you can carry — useless on Elisia and on werewolves" },
    et_spear:     { name: "Eternial spear", desc: "A golden spear that flies true and cuts half as deep again. Thrown, then picked back up" },
    holy_water:   { name: "Bottle of holy water", desc: "Clear water that glows faintly gold. Elisia's gift" },
    unholy_water: { name: "Bottle of unholy water", desc: "Black-red water torn from Elisia's dark form" },
    unholy_tiara: { name: "Unholy tiara", desc: "Elisia's black crown. Few dark forms leave it behind" },
    // update 36: the one canteen in the game
    water_bottle: { name: "Water bottle", desc: "Idris's leather canteen. Fill it at any water and it keeps you drinking in the desert heat" },
    super_energy_drink: { name: "Super energy drink", desc: "The blue can. +40% energy in one gulp" },
    axe:          { name: "Axe", desc: "Twice the knife's bite, longer reach — and three branches per chop" },
    needle:       { name: "Sewing needle", desc: "For serious stitching. Snaps one time in five" },
    thread:       { name: "Thread", desc: "Spun from rope at the crafting table" },
    wolf_bag:     { name: "Wolf bag", desc: "Wear it and every inventory slot holds 20. Hans pays for spares" },
    goggles:      { name: "Night vision goggles", desc: "Hold them at night and the dark turns green daylight" },
    raw_goat:     { name: "Raw goat meat", desc: "Mountain game — cook it over any fire" },
    cooked_goat:  { name: "Roast goat", desc: "+20% food — the richest common meat there is" },
    goat_horn:    { name: "Goat horn", desc: "A rare curved trophy" },
    climbing_anchor: { name: "Climbing anchor", desc: "Hold TWO and select them — the mountain's sheer faces open up" },
    silver_bar:   { name: "Silver bar", desc: "Stolen from the wolf statue. The whole den smells it — Jabb pays well" },
    hammer:       { name: "Hammer", desc: "A smith's hammer — anvil work needs it. Jabb leaves a spare out daily" },
    broken_hook:  { name: "Broken hook", desc: "Bent iron from under a rock. Hammer it into a climbing anchor at the anvil" },
    lit_torch:    { name: "Burning torch", desc: "Alive with fire — hold it to push back the night" },
    crossbow:     { name: "Crossbow", desc: "A hunter's crossbow — stores up to 100 arrows inside. You must LEARN to use it first" },
    arrow:        { name: "Arrow", desc: "A crossbow bolt. Select it and HOLD left-click to load it into your crossbow" },
    silver_arrow: { name: "Silver arrow", desc: "Silver-tipped — the only bolt a werewolf fears, and 25% sharper against everything" },
    feather:      { name: "Chicken feather", desc: "Light and true — fletching for arrows" },
    pestle:       { name: "Pestle and mortar", desc: "Crushes items to dust. You must LEARN to use it first" },
    silver_dust:  { name: "Silver dust", desc: "Ground from a silver dagger — the heart of a silver arrow" },
    chocolate:    { name: "Chocolate bar", desc: "+15% food — a survivor's sweet ration" },
    death_compass:{ name: "Compass of death", desc: "Never lost on death — its bone needle points to where you last fell" },
    scroll_spear: { name: "Scroll: spear crafting", desc: "Use it to LEARN how to craft a bound spear" },
    scroll_arrows:{ name: "Scroll: arrow crafting", desc: "Use it to LEARN how to fletch arrows" },
    scroll_silver_arrows: { name: "Scroll: silver arrows", desc: "Use it to LEARN how to fletch silver arrows" },
    scroll_pestle:{ name: "Scroll: pestle and mortar", desc: "Use it to LEARN how to crush items to dust" },
    scroll_climb: { name: "Scroll: tree climbing", desc: "Use it to LEARN to climb trees (two anchors required)" },
    scroll_crossbow_use: { name: "Scroll: using a crossbow", desc: "Use it to LEARN how to shoot a crossbow" },
    rope:         { name: "Rope", desc: "Sturdy hemp rope — needed for a fishing rod" },
    branch:       { name: "Wooden branch", desc: "Cut from trees with a knife. Fuel for a campfire, part of a rod" },
    tinderbox:    { name: "Tinderbox", desc: "Lights campfires anywhere — and one very big lamp" },
    fishing_rod:  { name: "Fishing rod", desc: "Cast it at the lake shore" },
    raw_fish:     { name: "Raw fish", desc: "Cook it over any fire" },
    cooked_fish:  { name: "Cooked fish", desc: "+10% food" },
    machete:      { name: "Machete", desc: "Bill's reward. Heavy, sharp, decisive" },
    torch:        { name: "Torch", desc: "Light it with a tinderbox or at a campfire — carry light into the night" },
    wine:         { name: "Old wine", desc: "+20% health, +20% food — but the world will sway for a minute" },
    croc_skin:    { name: "Crocodile skin", desc: "Tough scaled hide — a rare trophy" },
    // update 29: Dirk's farm
    raw_beef:     { name: "Raw beef", desc: "Fresh from the pasture — cook it at a furnace or a campfire before you eat it" },   // update 30
    cooked_beef:  { name: "Cooked beef", desc: "+20% food — a hearty steak, cooked through" },
    blueberries:  { name: "Bunch of blueberries", desc: "+5% food on their own — five of them crown a bowl of yogurt, or buy a lemon from Dirk" },
    lemon:        { name: "Lemon", desc: "Sour and sharp — sets warm milk into yogurt, once you know how" },
    bowl:         { name: "Empty bowl", desc: "Carved from two branches. Use it on a cow to fill it with milk" },
    bowl_milk:    { name: "Bowl of milk", desc: "Fresh and warm. Heat it at a stove or campfire with a lemon to make yogurt — if you have studied the scroll" },
    bowl_yogurt:  { name: "Bowl of yogurt", desc: "Plain yogurt. Mix in FIVE bunches of blueberries to finish the dish" },
    bowl_yogurt_blueberries: { name: "Yogurt with blueberries", desc: "+20% food, +20% health, wakes low energy to 25% — the empty bowl comes back to you" },
    scroll_yogurt:{ name: "Scroll: yogurt with blueberries", desc: "Use it to LEARN how to turn milk into blueberry yogurt" },
  },

  torchLitMsg: "The torch flares up. The dark backs away.",
  torchNeedsFire: "You need a tinderbox — or hold it into a burning campfire.",
  torchAlreadyLit: "The torch is already burning.",
  billCoffee: "Have a coffee with Bill (free, once a day)",
  billCoffeeUsed: "Bill taps his empty pot. No more coffee today, friend.",
  billCoffeeMsg: "Bill pours you a steaming cup. Warmth crawls back into your bones…",

  branchCut: "You cut a wooden branch from the tree",
  fireLit: "The campfire crackles to life — it will burn for a minute",
  fireNeedsTinder: "You need a tinderbox to light this",
  fishCast: "You cast the line…",
  fishCaught: "Something bites — a fish!",
  fishNeedRod: "You need a fishing rod to fish here",
  crocWarning: "The water stirs…",
  lightBeacon: "Light the beacon",
  beaconNeedsTinder: "The wick is cold. A tinderbox would light it",
  beaconLit: "The beacon roars to life! The lighthouse will guide you home.",
  lighthouseSafe: "Nothing can reach you inside the lighthouse.",
  deathBagPrompt: "Recover your items",
  deathBagDropped: "Your belongings were left where you fell. You have 15 minutes to find them.",
  deathBagRecovered: "You recovered your belongings",
  deathBagGone: "Your belongings are gone — the forest keeps what it takes.",
  eggTake: "Take a T-Rex egg",
  eggTaken: "The egg is warm. You cannot run while carrying it.",
  eggMother: "Behind you, far away, something ENORMOUS begins to move…",
  eggReturn: "Return the egg to the nest",
  eggReturned: "You lay the egg back. The great footsteps slowly fade away…",
  eggDrop: "You set the T-Rex egg down",
  eggPickBack: "Pick the T-Rex egg back up",
  eggToBill: "Give Bill the T-Rex egg",
  billEggThanks: "By my beard… a living T-Rex egg! You have a friend for life. I'll patch you up whenever you're hurting — and take this machete. Lose it, and ten chicken eggs buys you another.",
  billHeal: "Let Bill patch you up",
  billHealed: "There. Good as new, friend.",
  billMachete: "New machete for 10 eggs",
  billMacheteGiven: "Keep a better grip on this one, eh?",
  motherNear: "The ground shakes. HER footsteps. Do not let her see you.",

  cooked: "Cooked",
  mobSprint: "RUN", mobSneak: "SNEAK", mobJump: "JUMP", mobAct: "USE",
  // update 24: ONE-word labels for the mobile context button — a different
  // word for every situation, never a sentence
  mobOpen: "OPEN", mobClose: "CLOSE", mobTake: "TAKE", mobSleep: "SLEEP",
  mobCook: "COOK", mobCraft: "CRAFT", mobForge: "FORGE", mobTalk: "TALK",
  mobSit: "SIT", mobPray: "PRAY", mobLight: "LIGHT", mobSteal: "STEAL", mobClimb: "CLIMB",
  mobGive: "GIVE", mobReturn: "RETURN", mobUse: "USE", mobSlide: "SLIDE",
  mobFill: "FILL",   // update 36
  // the on-screen controls, explained (Controls menu, on-screen mode only)
  touchControlsList: [
    ["Left stick", "Move"],
    ["Drag the right half", "Look around"],
    ["RUN", "Hold to run (drains energy and hunger faster)"],
    ["SNEAK", "Sneak on/off (quiet — T-Rexes hear less)"],
    ["JUMP", "Jump (costs energy)"],
    ["USE", "Use the selected item: eat food, drink, apply bandage — or attack with a blade"],
    ["OPEN / SLEEP / COOK…", "The golden button above RUN appears when something is in reach — tap it to interact"],
    ["Hotbar", "Tap an item to select it"],
    ["❚❚", "Pause menu (top-left corner)"],
  ],

  // ---- update 8 ----
  locations: {
    temple: "Old Temple",
    hut: "Bill's Hut",
    lighthouse: "Lighthouse",
    lake: "The Lake",
    nest: "T-Rex Nest",
    container: "Sea Container",
    camping: "The Camping",
    ruinsv: "Old Ruins",
    mountain: "Rocky Mountain",
    farm: "Dirk's Farm",
    tent: "Idris's Tent",
    oasis: "The Oasis",
    portal_red: "Red Portal", portal_green: "Green Portal", portal_yellow: "Yellow Portal",   // update 37
    portal_blue: "Blue Portal", portal_white: "White Portal",
    eternius: "Eternius City",   // update 39
  },
  // update 39: Eternius City
  et: {
    talk: "Talk to", trade: "Trade with", fish: "Cast the line", fishing: "You cast the line into the dark water...",
    purse: "Your purse: %n Eternial coins", coinsShort: "c", coinsGot: "+%n Eternial coins", noCoins: "You do not have enough coins.",
    buyHead: "For sale", sellHead: "They buy from you", buy: "Buy", sell: "Sell", sellSure: "Sure? Sell for %n",
    rareWarn: "Warning: everything sold here is rare. Sold is sold — the Eternials never sell these back.",
    nothingToSell: "Nothing in your pack that this stall wants.", nothingRare: "Nothing rare in your pack.",
    bought: "Bought: %i", sold: "Sold %i for %n coins", noBottle: "You need a water bottle for that.", fillWater: "Fill your water bottle",
    prayed: "You pray at the golden altar. Your hunger and your wounds are gone.",
    sleepFor: "Sleep at the inn — %n coins", rexWarn: "A chained beast. Keep away from its reach.",
    vaultOpen: "The vault door", vaultLocked: "Locked. The king holds the only key.", vaultOpened: "The golden door slides aside.",
    kingName: "King Anhurath", innName: "Meriti the innkeeper", keeperName: "Old Tehenu, Keeper of Tales", cookedMeat: "cooked meat (any)",
    kingIntro: "You walk under my mountain, stranger, and you still breathe. Good. Eternius has work for such as you.",
    kingTask: "Bring me %need and the treasury pays you %r Eternial coins.",
    kingGive: "Hand it over", kingThanks: "The treasury has paid you. Come back tomorrow — there is always more to be done.",
    taskDone: "The king's task is done: +%r coins", keyGot: "The king trusts you now: he gives you the key to the vault.",
    innLines: ["Welcome, traveller. A bed here costs %n coins a night, and nothing with teeth ever comes down these stairs.", "Sleep when the sky in the shaft goes dark. Press on a bed to lie down."],
    keeperLater: "Let the words settle first. Walk a while, then come back and I will tell you the next part.",
    keeperDone: "You have heard every tale I keep. Perhaps one day you will bring me a new one.",
    guardLines: ["Move along. The king's peace holds inside these walls.", "Keep away from the chained one. It has eaten faster things than you.", "Eternial steel is sold at the smith's. It will not save you from her. Nothing gold does."],
    maleLines: ["Three metres tall and still I look up at the shaft every morning. The light never gets old.", "The forest people never come this far. You are the first in a long while.", "Coins, stranger. The stalls take nothing else — not teeth, not fur, not promises.", "My grandfather laid the gold on that dome. It took him forty years and it still shines."],
    femaleLines: ["Welcome to Eternius. Mind the steps down to the plaza, they are cut for our legs, not yours.", "The river below is cold and full of fish. Neferu sells the rods.", "Sethra pays well for strange things. Too well, some say.", "Old Tehenu sits by the river. He talks slowly, but he knows everything."],
    foodLines: ["Fresh from the terraces and the river. Coins on the counter, please.", "You look hungry. Everyone who comes over the sand looks hungry."],
    toolsLines: ["A knife, a rope, a torch — what the sand takes, I sell back.", "Everything here is made by Eternial hands. It lasts."],
    rareLines: ["I buy what nobody else can find. Show me.", "Once it is mine, it stays mine. Think before you sell."],
    smithLines: ["Gold holds an edge better than you would think — with a little green stone in the alloy.", "None of my blades will bite her. Do not ask me why. Ask Tehenu."],
    foodBlurb: "Food, drink, a fishing rod, and water for your bottle. Neferu buys food too.",
    toolsBlurb: "Simple tools, made to last. Khamet buys tools back.",
    rareBlurb: "Sethra buys rare things and sells nothing. Every sale here is final.",
    smithBlurb: "Eternial weapons: gold, green stone, and an edge beyond iron and silver. They cannot harm Elisia or a werewolf.",
    chapters: [
      { title: "The First Tale — Out of the Sand", lines: ["Long before your kind walked the forest, we came up out of the sand. Not from a ship, not from the sky. From below. The mountain was hollow and it called us, and we answered."] },
      { title: "The Second Tale — Ozrek the Spearbearer", lines: ["The statue in the courtyard is Ozrek. He walked the shaft of light alone and came back with the first gold. He chained the first beast to guard the gate. It is not the same beast, but it is the same chain."] },
      { title: "The Third Tale — The Shaft", lines: ["The hole in the mountain is not a hole. It is a wound the sun made when it first found us, and we built the altar where the light lands so that it would never leave."] },
      { title: "The Fourth Tale — The Beasts", lines: ["The great lizards ruled the forest before the mist came. We learned to chain them, not to kill them. A killed beast is a beast whose brothers come looking."] },
      { title: "The Fifth Tale — Elisia", lines: ["She sang in the mist before she turned grey, and we sang back. When the singing became laughter we closed the gate. No gold cuts her. Only the teeth of the beasts she feeds on."] },
      { title: "The Sixth Tale — The Five Gates", lines: ["Eternial hands raised the portals, one for each corner of the world and a white one in the dark. We lost the fifth long ago. Perhaps you will find where it stands."] },
      { title: "The Seventh Tale — The Prophecy", lines: ["A stranger will come over the sand with a purse of our coins and a tooth of the beast. The stranger will walk through the White Gate and the mist will follow. Whether it lifts or thickens, the tale does not say."] },
    ],
  },
  // update 37: the portals
  portal: {
    investigate: "Investigate portal", use: "Use portal",
    locked: "The stone is cold. Something still binds it.",
    red: "Apple trees you have picked from: %n of %m.",
    dontGo: "Don't go",
    pickHint: "W A S D choose a place · F go",
    goTo: "Go to %p",
    yellow: "Days in a row without starving: %n of %m.",
    green: "Different chests opened today: %n of %m. A snake's bite, or the dawn, starts you over.",
    blue: "Different beds slept in: %n of %m.",
    white: "Portals awakened: %n of %m.",
    awake: "The ring hums. It will carry you anywhere you have already been.",
    activated: "%p awakens!",
    whereTo: "Where to?",
    noDest: "You have found nowhere else to go yet.",
    arrive: "The light lets go of you.",
  },
  discovered: "Discovered",
  huntImperator: "T-IMPERATOR",
  elisiaFeeds: "She feeds. RUN.",
  imperatorNear: "Something bigger than a T-Rex is out there.",
  mapHint: "Named places appear on the map once you have found them yourself.",
  soundToggle: "Sound on/off",
  soundVolume: "Volume",
  openHatch: "Open the trapdoor",
  closeHatch: "Close the trapdoor",
  hutChestLocked: "Bill keeps this chest locked. “Bring me three T-Rex eggs, friend — then what's mine is yours.”",
  hutChestTitle: "Bill's wooden chest",
  billEggMore: "Another one! By my beard. Bring me a third and my old wooden chest is yours to use.",
  billEggChest: "THREE living T-Rex eggs. You mad, wonderful lunatic — the wooden chest by the bed is yours now. Store whatever you like in it.",
  // ---- update 9: the camping ----
  talkToHans: "Talk to Hans",
  talkToEmily: "Talk to Emily",
  talkToTimo: "Talk to Timo",
  hansTitle: "Hans",
  emilyTitle: "Emily",
  timoTitle: "Timo",
  hansLines: [
    "Easy there — you're inside the fence, you're fine. Name's Hans. We've been camped here since our plane went down beyond the ridge.",
    "The big ones don't bother with the camp. Don't ask me why — maybe the fire, maybe the fence. But mark my words: if one is already after you, no fence in this forest will change its mind.",
  ],
  hansAskMystery: "Ask about the dinosaurs",
  hansMysteryLines: [
    "Nobody knows what woke them. Emily thinks the island never let them die out. I think something in that old temple kept them asleep — and somebody opened a door that should have stayed shut.",
    "The MOTHER is the heart of it. All the others move around her like planets around a sun. Steal from her nest and the whole forest holds its breath.",
  ],
  hansAskDanger: "Ask about the dangers",
  hansDangerLines: [
    "The T-Rexes hunt with their ears. The wolves come only at night — silver is the only thing that bites them back. The water… don't stand in the water too long, friend.",
    "And stay clear of the old ruins east of here. Something lives there that makes a T-Rex look like a chicken. It watches those broken houses like a mother watches a cradle. Which, I suppose, it is.",
  ],
  hansAskTimo: "Ask about his friend Timo",
  hansTimoLines: [
    "So it's true you go where others don't… Then hear me out. Our third man, TIMO, never made it back. He took shelter in the old ruined village to the far north-east — past the lake, deep in the jungle.",
    "He's holed up in the stone house there. Alive, last we heard him on the radio — but a BEAST guards that village. Bring Timo home and everything we have is yours: the red tent, our storage chest, all of it.",
  ],
  emilyLines: [
    "Oh! A face I don't know. I'm Emily. Sit by the fire, it keeps the shakes away.",
    "Hans acts tough, but we don't sleep much. Every night the howling gets a little closer.",
  ],
  emilyAskTips: "Ask for survival tips",
  emilyTipsLines: [
    "Crouch when you move — they hear you long before they see you. Dry branches are traitors. And if one spots you, put a boulder or a thick tree between you and it, then stay put.",
    "Carry a torch at night, cook everything you catch, and never — NEVER — sprint with your energy low. That's how people end up as bones in this forest.",
  ],
  emilyAskMother: "Ask about the Mother",
  emilyMotherLines: [
    "I saw her once, across the lake. I thought a hill was moving. If you're ever in an open field and the ground starts to shake — it's already too late.",
    "They say she only leaves her nest when someone takes what's hers. So whatever you do out there… think twice before you touch an egg.",
  ],
  hansQuestActive: "Timo is still out there, friend. The stone house, north-east ruins. Bring him home.",
  hansQuestDone: [
    "You actually did it. TIMO! By the fire, look who's back!",
    "The red tent is yours, friend — sleep whenever you need. And take the chest too. What's ours is yours. Forever.",
  ],
  timoRuinsLines: [
    "You— you're real? Keep your voice down! That THING circles the village all day. I can hear its claws on the stones.",
    "I can walk. Get me to the camp — west side of the island, past Bill's hut if we keep a straight line. Stay close to me, move quiet, and PLEASE don't let it see us.",
  ],
  timoFollowBtn: "Let's go — follow me",
  timoCampLines: [
    "Air. Fire. PEOPLE. I never thought I'd see this again… Thank you. I mean it. You ever need anything, ask Hans — he owes you now, and Hans always pays his debts.",
  ],
  timoFollowing: "Timo follows close behind you. Hunters will notice TWO of you far more easily…",
  timoDied: "You died — Timo fled back to the ruins. Find him there again.",
  timoWaits: "Timo hides at the stone house in the old ruins…",
  questRedTentLocked: "Hans shakes his head: “The red tent belongs to Timo's rescue. Bring our friend home first.”",
  questChestLocked: "The chest is Hans's. “Bring Timo home,” he says, “then what's ours is yours.”",
  campHome: "Inside the fence the forest keeps its distance — as long as nothing followed you in.",

  // ---- update 9: the old ruins ----
  spinoSpotted: "THE GUARDIAN HAS SEEN YOU — RUN OR DIE!",
  spinoNear: "Heavy claws click on broken stone…",
  babyScream: "The hatchlings SHRIEK — the whole forest hears it. SHE is coming.",
  prayPrompt: "Pray at the altar",
  prayed: "Warmth settles in your chest. Your hunger is gone.",
  prayedAlready: "The altar is silent. Come back tomorrow.",
  barTinderbox: "Take the tinderbox",
  fridgePrompt: "Open the refrigerator",
  fridgeWine: "Behind rotten jars: a dusty bottle of wine.",
  fridgeEmpty: "Empty. Maybe something cools here again tomorrow.",
  coolboxPrompt: "Open the cool box",
  invMoveHint: "[1-8] or [←] [→] pick a slot · [F] lift, [F] drop · or drag with the mouse",
  axeFound: "An AXE — twice the knife, and it eats trees whole.",
  drankSuper: "The blue can hits like lightning. +40% energy.",
  needleBroke: "the needle SNAPPED.",
  wolfBagOn: "You sling the wolf bag over your back. Every slot now holds 20.",
  wolfBagAlready: "You already wear one. Hans buys spares — ask him.",
  hansBagIntro: "Say — is that wolf-stitch work on your back? I COLLECT wolf pieces. Bring me a spare bag and I'll make it worth the effort.",
  hansSellBag: "Trade a spare wolf bag",
  hansBagThanks: "Ha! Look at that stitching. A deal's a deal — here, take this.",
  hansBagReward: "Hans hands you:",
  cookChoose: "Different foods aboard — HOLD the one you want to cook.",
  cookedDropped: "no room, it lands at your feet.",
  hintWolfBag: "wear it — every slot holds 20",
  hintAnchor: "hold 2, select them at the cliff — then you can climb",
  hintSilverBar: "the den smells it — bring it down to Jabb",
  climbNeed: "The rock face is sheer. You need TWO climbing anchors — held and selected.",
  slideDown: "Slide down the cliff — costs 30% health",
  slideOuch: "The scree chews you up the whole way down. −30% health",
  stealBar: "Steal the silver bar",
  barStolen: "The silver leaves the statue's paws — and the WHOLE DEN wakes.",
  // ---- update 27: scrolls, crossbow, canopy ----
  scrollLearned: "The scroll crumbles to dust — the knowledge is YOURS now.",
  scrollFound: "A LEARNING SCROLL — use it, and its knowledge is yours forever.",
  crossbowFound: "A CROSSBOW! Learn its scroll, feed it arrows — and death comes from a distance.",
  crossbowUnlearned: "You turn the crossbow over in your hands… you have no idea how to load it. A scroll must teach you.",
  crossbowEmpty: "Click — the crossbow is EMPTY. Load arrows or carry some in your pack.",
  crossbowLoaded: "arrows in the crossbow",
  crossbowStored: "You press arrows into the crossbow's magazine.",
  crossbowFull: "The magazine is full — 100 arrows is all it holds.",
  arrowImmune: "The arrow SNAPS off its hide — no bolt hurts a dinosaur.",
  arrowWolfImmune: "The wolf swats the arrow aside — only SILVER flies true against it.",
  arrowLost: "The arrow shatters where it lands.",
  pestleUnlearned: "You weigh the stone bowl in your hands… a scroll must teach you the craft.",
  pestleNothing: "Nothing in your pack is worth crushing — the mortar waits for a SILVER DAGGER.",
  pestleConfirm: "Crush your SILVER DAGGER into 10 silver dust? This cannot be undone — the dagger will be GONE.",
  pestleCrush: "Crush it",
  pestleCancel: "Keep the dagger",
  pestleCrushed: "The dagger cracks, shears, and falls to glittering dust. TEN measures of silver.",
  climbUnlearned: "The bark offers no grip you can use — a scroll must teach you the way of the canopy.",
  climbTree: "Climb the tree",
  climbNeedAnchors: "Tree climbing needs TWO climbing anchors — held and selected.",
  treeItemFound: "Something is wedged in the branches…",
  treeSafe: "The wolf circles the trunk below… hold on up here.",
  wolfGaveUp: "The werewolf snarls one last time — and slinks away.",
  fallOuch: "The ground hits back — that fall HURT.",
  hansScrollGift: "Hans presses a scroll into your hands: “Timo's old crossbow manual. He'd want a fighter to have it.”",
  compassPoints: "The bone needle trembles",
  compassIdle: "The compass of death sleeps — it wakes when you fall.",
  talkToJabb: "Talk to Jabb",
  jabbTitle: "JABB — dwarf of the mountain",
  jabbLines: [
    "Hmph. A soft-lander, up here. The bed's yours if you need it — mountain rule.",
    "You want my STORAGE? Earn it. The wolves up top guard a SILVER BAR in their cave. Bring it to me and I'll arm you proper for it.",
    "Mind the sheer faces. No anchors, no climb — the mountain doesn't negotiate.",
  ],
  jabbLinesDone: [
    "The silver sings on my anvil, friend. My box, my bed, my coffee — all yours.",
    "The goats are good eating, if you can catch them. Leave some for me.",
  ],
  jabbGiveBar: "Hand over the silver bar",
  jabbThanks: [
    "HA! You actually walked it out of the den. Here — a SILVER DAGGER, dwarf-honed. And my storage box is yours.",
  ],
  jabbCoffeeBtn: "Drink a coffee with Jabb",
  jabbCoffeeMsg: "Jabb's coffee could strip rust. Your legs hum with energy.",
  jabbChestTitle: "JABB'S STRONGBOX",
  jabbChestLocked: "Jabb grunts: the box is for silver-bringers. Ask him about the cave.",
  useAnvil: "Smith at the anvil",
  trikeImmune: "Your blade skips off the frill. TOO BIG. TOO STRONG. Step aside instead.",
  trikeStuck: "Its horns SLAM into the dead wood and STICK — run. NOW.",
  rockChest: "The rock SHATTERS — a treasure chest was buried beneath it!",
  rockHook: "The rock SHATTERS — something metal glints in the rubble.",
  smithTitle: "THE ANVIL",
  smithHint: "Dwarf-work: hammer metal into what the forest can't give you.",
  smithBtn: "Smith",
  hintGoggles: "hold them at night — the dark turns green",
  hintSewing: "crafting supplies — the wolf bag needs them",
  drunkStart: "The wine burns going down. The world starts to sway…",
  drunkEnd: "Your head clears. The forest stops swaying.",
  drunkLabel: "DRUNK",
  ruinsBedHint: "An intact bed among the ruins — a rare mercy.",

  // ---- update 11: the T-Rex hunt ----
  spearHit: "The spear bites deep — it BLEEDS!",
  spearHead: "A PERFECT THROW — straight into the skull!",
  spearImmune: "The spear snaps against that hide like a toothpick. RUN.",
  trexEnraged: "Wounded and FURIOUS — it will not stop now!",
  trexSlain: "THE T-REX FALLS. The ground shakes one last time.",
  huntTrex: "T-REX",
  huntEnraged: "ENRAGED",
  hintSpear: "throw it — aim for the skull",

  motherSees: "OPEN GROUND — SHE SEES YOU. RUN FOR THE TREES!",
  motherGrab: "Her jaws close around you…",
  deadMother: "The mother caught you in the open. One bite was enough.",
  containerSafe: "Steel walls. Nothing out there can open that door.",
  eggRegrown: "Far away, in the nest, a new egg settles into the mud…",
  gfxBtn: "Graphics",
  gfxTitle: "GRAPHICS",
  gfxResolution: "Render resolution",
  gfxLow: "Low",
  gfxMedium: "Medium",
  gfxHigh: "High",
  gfxNative: "Native",
  gfxActive: "Rendering at",
  gfxMsaaLabel: "Antialiasing (MSAA)",
  gfxOn: "On",
  gfxOff: "Off",
  gfxMsaaNote: "Off is usually fine - at High and Native the picture is already smoothed by downscaling.",
  gfxReloadNote: "Reload to apply — this setting takes effect the next time the game loads.",
  gfxDgpuLabel: "Use dedicated graphics card (if available)",
  gfxGpuLabel: "Graphics card:",
  // update 26: quality presets + dynamic resolution
  gfxPresetLabel: "Quality preset",
  gfxPresetLow: "Low", gfxPresetMedium: "Medium", gfxPresetHigh: "High", gfxPresetUltra: "Ultra",
  gfxPresetCustom: "Custom",
  gfxDynresLabel: "Dynamic resolution",
  gfxDynresNote: "When the frame rate dips for a while, the render resolution steps down a notch — and back up when there is headroom.",

  // ---- update 29: Dirk's farm ----
  talkToDirk: "Talk to Dirk",
  dirkTitle: "DIRK — the farmer",
  dirkLines: [
    "Dirk wipes his hands on his apron. \"A visitor! Mind the cows — they're gentle until somebody isn't.\"",
    "\"Blueberries out back, milk in the pasture, a bed upstairs if the night catches you. And Duco — Duco is the best dog in this whole cursed forest.\"",
    "\"I trade goods for goods. Put the right thing on the table and it's yours.\"",
  ],
  dirkAskFarm: "Ask about the farm",
  dirkFarmLines: [
    "\"Six cows, one dog, a field of blueberries and a house my grandfather raised with his own hands. The beasts out there leave us be — except the wolves. Some nights they come for the cows.\"",
    "\"Give Duco a bowl of blueberry yogurt and watch him lose his mind. He'll even help you pick, if you're already rested.\"",
  ],
  dirkShopBtn: "See what Dirk trades",
  dirkShopTitle: "Dirk's trade",
  dirkShopHint: "Goods for goods. Each row shows what Dirk gives — and what he wants for it.",
  dirkBuyBtn: "Trade",
  dirkFor: "for",
  dirkNoGoods: "Dirk shakes his head: \"That's not the price, friend.\"",
  dirkSold: "Traded",
  dirkEggPrice: "one LIVING T-Rex egg, carried in your hands",
  dirkEggNeeded: "\"Bring me a living T-Rex egg in your own two hands and we'll talk.\"",
  dirkScrollKnown: "\"You already know how to make it. Keep your egg.\"",
  dirkScrollBought: "Dirk takes the egg with both hands, eyes wide, and slides an old scroll across the table. \"The storage chest upstairs is yours to use now.\"",
  dirkChestTitle: "Dirk's storage chest",
  dirkChestLocked: "Locked. Dirk only opens it for whoever brings him a living T-Rex egg.",
  cowMilk: "Milk the cow",
  cowMilkNeedBowl: "You need an EMPTY BOWL to milk a cow.",
  cowMilked: "Warm milk fills the bowl.",
  cowAngry: "The cow turns on you — you started it.",
  killedCow: "You killed the cow",
  cowRaid: "A werewolf is in the pasture — the cows are screaming!",
  cowRaidGone: "The wolf drags its meal into the trees. The pasture goes quiet.",
  pickBerries: "Pick blueberries",
  crateTitle: "Blueberry crate",
  cratePrompt: "Open the blueberry crate",
  crateHint: "A crate for blueberries only. Duco fills it while he helps you pick.",
  crateCount: "Blueberries in the crate",
  crateStoreAll: "Store all your blueberries",
  crateTake10: "Take 10",
  crateTakeAll: "Take all that fit",
  crateFull: "The crate is full",
  crateEmptyMsg: "The crate is empty",
  crateNoBerries: "You have no blueberries to store",
  cratePackFull: "Your pack is full",
  ducoGive: "Give Duco the blueberry yogurt",
  ducoNoHit: "Duco looks up at you with big brown eyes. His cuteness overpowers your ability to attack.",
  ducoEnergy: "Duco licks your hands and barks with joy. You feel completely rested!",
  ducoHelps: "Duco barks happily — he'll pick blueberries with you until nightfall!",
  ducoHelping: "DUCO IS PICKING BLUEBERRIES WITH YOU",
  ducoDone: "Night falls. Duco trots off to his mat — enough picking for today.",
  yogurtUnlearned: "You have no idea how to curdle milk — a scroll must teach you first.",
  yogurtNeedsLemon: "Yogurt needs a LEMON in your pack — the milk alone will not set.",
  yogurtNeedsBerries: "Plain yogurt wants FIVE bunches of blueberries — you have %n.",
  yogurtMade: "Five bunches of blueberries sink into the bowl. Yogurt with blueberries!",
  bowlBack: "the empty bowl goes back in your pack",
  bowlDropped: "no room — the empty bowl lands at your feet",
  hintYogurtMix: "mix in five bunches of blueberries",
  hintBlueberries: "eat — or keep five for a bowl of yogurt / a lemon from Dirk",
  hintLemon: "sours warm milk into yogurt at a stove or campfire (with the scroll)",
  hintBowlMilk: "heat it at a stove or campfire with a lemon — once you know yogurt",
  hintBowl: "empty — use it on a cow for milk",
  farmSitDown: "Sit at the dinner table",
  farmSitChair: "Sit down on the chair",   // update 33: the armchair is not a dinner table
  // update 30: the taps
  tapPrompt: "Drink from the tap",
  tapDrink: "Cold well water. Energy +10%.",
  tapFullEnergy: "Cold and clear — you are wide awake already.",
  hintRawBeef: "cook it at a furnace or a campfire first",
  mobDrink: "DRINK",
  // update 31: the attic
  climbLadder: "Climb the ladder to the attic",
  climbDownLadder: "Climb down from the attic",
  atticUp: "The hatch swings back. Dust, crates, and light through the gable.",
  atticDown: "Back down on the landing.",
  // update 32: Duco's blueberry — a toy, never an item
  toyPick: "Pick up Duco's blueberry",
  toyHint: "Left-click to throw it — hold to throw further",
  toySteal: "Careful with toys that belong to someone else — Duco's blueberry stays on the farm.",
  toyBack: "Duco drops the blueberry at your feet.",
  mobToy: "PLAY",
  mobMilk: "MILK",
  mobPick: "PICK",
};
